import type { PremiumServicePageData, PremiumServiceTheme } from "./components/FireAlarmPremiumPage";

export type ServiceGroupKey = "fire" | "security" | "emergency" | "smart" | "compliance";

export type ServiceGroup = {
  key: ServiceGroupKey;
  route: string;
  label: string;
  theme: PremiumServiceTheme;
  landing: PremiumServicePageData;
  pages: PremiumServicePageData[];
};

function makePage(page: PremiumServicePageData): PremiumServicePageData {
  return page;
}

const heroContactUs = {
  heroSecondaryCta: "Contact us now",
  heroSecondaryHref: "/book-now",
};

const commonSuitableFor = [
  "Commercial buildings",
  "Residential developments",
  "Managed properties",
  "Offices and retail units",
  "Education and care environments",
  "Facilities management portfolios",
];

const firePages = [
  makePage({
    slug: "fire-alarm-systems",
    title: "Fire Alarm Systems",
    eyebrow: "Early warning & dependable detection",
    intro: [
      "Helix delivers the design, installation, and maintenance of fire alarm systems for a wide range of buildings, helping ensure early warning, reliable protection, and ongoing compliance.",
    ],
    heroImage: "/images/001 - FIRE SYSTEMS/001 - Fire Alarm Systems/Tech HQ and glass corridor 2.png",
    heroAlt: "Modern technology headquarters with glass corridor interior",
    sectionTitle: "Professional fire alarm installation",
    sectionBody: [
      "Every fire alarm system should be designed around the specific needs of the building — not forced into a one-size-fits-all solution.",
      "Helix provides complete support from initial survey and system design through to installation, commissioning, maintenance, and clear documentation for ongoing compliance and long-term safety management.",
      "Well suited to commercial buildings, residential developments, managed properties, and multi-occupancy environments.",
    ],
    servicesTitle: "Our fire alarm services include",
    services: [
      "Fire alarm design and planning",
      "Conventional fire alarm systems",
      "Addressable fire alarm systems",
      "Fire alarm panel installation",
      "Smoke and heat detector installation",
      "Manual call point installation",
      "Sounder and beacon installation",
      "Commissioning and certification",
      "Fault finding and repairs",
      "Scheduled servicing and maintenance",
    ],
    featureCards: [
      { title: "Conventional Systems", text: "Ideal for smaller buildings divided into detection zones.", icon: "target" },
      { title: "Addressable Systems", text: "Better device identification for larger or more complex sites.", icon: "network" },
      { title: "Maintenance", text: "Keeping alarm systems serviced, reliable and compliant.", icon: "shield" },
    ],
    suitableFor: [
      "Commercial buildings",
      "Residential developments",
      "Managed properties",
      "Offices and retail units",
    ],
    ctaTitle: "Protect your property with a professionally installed fire alarm system.",
    ctaText: "Talk to Helix today and arrange a survey or quote.",
    ctaButton: "Contact us now",
  }),
  makePage({
    slug: "fire-extinguishers-supply-servicing",
    title: "Fire Extinguishers (Supply & Servicing)",
    eyebrow: "Correct extinguishers for the right risk",
    intro: [
      "Helix supplies, installs and services fire extinguishers for commercial, residential and managed properties.",
      "We help ensure the correct extinguisher types are positioned, maintained and documented for the risks within your building.",
    ],
    heroImage: "/images/001 - FIRE SYSTEMS/002 - Fire Extinguishers/Wall Mounted UK Fire Extinguishers in Modern Warehouse.png",
    heroAlt: "Wall mounted water foam and CO2 fire extinguishers with safety signage in a commercial building",
    sectionTitle: "Extinguisher supply, placement and servicing",
    sectionBody: [
      "Different fire risks require different types of extinguishers, making correct selection and positioning essential for effective fire protection.",
      "Helix provides a complete extinguisher service including supply, installation, commissioning, annual servicing, replacements, signage, and maintenance record management.",
      "Helping ensure extinguishers remain accessible, compliant, and appropriate for the environment they protect.",
    ],
    servicesTitle: "Our extinguisher services include",
    services: [
      "Water, foam, CO2, powder and wet chemical extinguishers",
      "Extinguisher supply and installation",
      "Commissioning and location planning",
      "Annual servicing and maintenance",
      "Refills and replacements",
      "Fire extinguisher signage",
      "Service records and documentation",
      "Basic user guidance",
    ],
    featureCards: [
      { title: "Right Type", text: "Extinguishers selected for the actual site risks.", icon: "target" },
      { title: "Right Place", text: "Visible, accessible and compliant positioning.", icon: "building" },
      { title: "Right Records", text: "Servicing and documentation kept clear.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need extinguishers supplied or serviced?",
    ctaText: "Book professional fire extinguisher support with Helix.",
    ctaButton: "Book a Survey",
    heroSecondaryCta: "Contact us now",
    heroSecondaryHref: "/book-now",
  }),
  makePage({
    slug: "aov-smoke-ventilation-systems",
    title: "AOV (Smoke Ventilation) Systems",
    eyebrow: "Smoke control for safer escape routes",
    intro: [
      "Automatic Opening Ventilation systems help control smoke movement during a fire and support safer evacuation routes.",
      "Helix installs and maintains AOV and smoke ventilation systems for residential, commercial and managed buildings.",
    ],
    heroImage: "/images/001 - FIRE SYSTEMS/003 - AOV Smoke Ventilation Systems/AOV residential daytime.png",
    heroAlt: "Automatic opening ventilation windows controlling smoke movement in a stairwell",
    sectionTitle: "Smoke ventilation that works with your fire strategy",
    sectionBody: [
      "AOV (Automatic Opening Ventilation) systems help protect stairwells, corridors, communal areas, and smoke shafts by allowing smoke to escape from key escape routes during a fire.",
      "Helix designs, installs, and maintains AOV systems, including integration with fire alarm systems where required, helping ensure systems remain compliant, reliable, and ready to operate when needed.",
      "Supporting safer evacuation routes and more effective smoke control during an emergency.",
    ],
    servicesTitle: "Our AOV services include",
    services: [
      "AOV system design and installation",
      "Window actuator installation",
      "Roof hatch and louvre vent systems",
      "Smoke shaft ventilation",
      "Stairwell and communal area ventilation",
      "Fire alarm integration",
      "Testing, servicing and repairs",
      "Compliance documentation",
    ],
    featureCards: [
      { title: "Smoke Control", text: "Ventilation planned around escape routes.", icon: "building" },
      { title: "Integration", text: "Linked to fire alarm systems where needed.", icon: "network" },
      { title: "Maintenance", text: "Operational checks and service records.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need reliable AOV or smoke ventilation support?",
    ctaText: "Talk to Helix about your building and escape route requirements.",
    ctaButton: "Discuss AOV Requirements",
    heroSecondaryCta: "Contact us now",
    heroSecondaryHref: "/book-now",
  }),
  makePage({
    slug: "fire-safety-signage",
    title: "Fire Safety Signage",
    eyebrow: "Clear routes, clear instructions",
    intro: [
      "Fire safety signage helps occupants understand escape routes, extinguisher locations and key safety instructions quickly.",
      "Helix supplies and positions practical signage as part of wider fire safety and compliance support.",
    ],
    heroImage: "/images/001 - FIRE SYSTEMS/004 - Fire Safety Signage/Fire safety signage in University Library.png",
    heroAlt: "Fire safety signage including exit and direction signs in a university library",
    sectionTitle: "Signage that supports safe evacuation and compliance",
    sectionBody: [
      "Effective fire safety signage should be clear, consistent, and positioned where it helps people make quick and informed decisions during an emergency.",
      "Helix reviews escape routes, equipment locations, and building layout to recommend and install appropriate fire safety signage tailored to the environment.",
      "Helping improve visibility, wayfinding, and overall emergency preparedness throughout the building.",
    ],
    servicesTitle: "Fire signage support includes",
    services: [
      "Fire exit signage",
      "Escape route direction signs",
      "Fire extinguisher identification signs",
      "Fire action notices",
      "Door and mandatory safety signs",
      "Signage placement reviews",
      "Replacement and refresh support",
      "Documentation for managed sites",
    ],
    featureCards: [
      { title: "Visible", text: "Signs positioned where people can see them", icon: "target" },
      { title: "Consistent", text: "A clear and understandable approach across the building", icon: "clipboard" },
      { title: "Compliant", text: "Placed according to current standards", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need fire safety signage reviewed or installed?",
    ctaText: "Helix can help make escape routes and equipment locations clearer.",
    ctaButton: "Review Fire Signage",
    heroSecondaryCta: "Contact us now",
    heroSecondaryHref: "/book-now",
  }),
];

const securityPages = [
  makePage({
    slug: "cctv-surveillance",
    title: "CCTV Surveillance",
    eyebrow: "Visual coverage that supports real oversight",
    intro: [
      "CCTV surveillance helps clients monitor entrances, shared spaces, circulation routes and high-risk areas with better visibility.",
      "Helix designs, installs and maintains CCTV systems that are practical to manage and configured around your site.",
    ],
    heroImage: "/images/002 - SECURITY SYSTEMS/001 - CCTV Systems/CCTV External 2.png",
    heroAlt: "External CCTV camera monitoring a commercial site",
    sectionTitle: "CCTV designed around the building",
    sectionBody: [
      "Effective CCTV systems rely on more than just cameras — correct placement, recording strategy, footage access, and long-term reliability are all essential.",
      "Helix designs CCTV systems around real operational requirements, helping clients improve site visibility, monitor activity, and review incidents with confidence.",
      "Supporting clearer oversight, incident review, and day-to-day site security management.",
    ],
    servicesTitle: "Our CCTV services include",
    services: [
      "Camera placement planning",
      "Internal and external CCTV",
      "Recording and storage setup",
      "Remote viewing configuration",
      "System upgrades",
      "Maintenance and fault support",
    ],
    featureCards: [
      { title: "Coverage", text: "Camera placement around high risk areas", icon: "target" },
      { title: "Review", text: "Recording configured for incident playback.", icon: "clipboard" },
      { title: "Support", text: "Maintenance and upgrade support over time.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need CCTV coverage designed around your site?",
    ctaText: "Book a CCTV review with Helix.",
    ctaButton: "Book a CCTV Review",
    ...heroContactUs,
  }),
  makePage({
    slug: "intruder-alarms",
    title: "Intruder Alarms",
    eyebrow: "Detection built around the site",
    intro: [
      "Intruder alarm systems protect buildings during unoccupied periods and trigger clear alerts when unauthorised access events occur.",
      "Helix installs and maintains alarm systems configured around entry points, risk areas and occupancy patterns.",
    ],
    heroImage: "/images/002 - SECURITY SYSTEMS/002 - Intruder Alarm Systems/Internal alarm keypad and PIR sensor.png",
    heroAlt: "Internal intruder alarm keypad and PIR sensor in a commercial building",
    sectionTitle: "Alarm systems configured for daily use",
    sectionBody: [
      "Every site has different access patterns, occupancy schedules, and after-hours security risks. An effective intruder alarm system should be designed around how the building is actually used day to day.",
      "Helix designs and installs practical, reliable intruder alarm systems that are easy to arm, disarm, manage, and maintain, helping clients improve security, reduce risk, and protect their premises with confidence.",
      "Supporting faster response to unauthorised access and improved protection outside operating hours.",
    ],
    servicesTitle: "Intruder alarm support includes",
    services: [
      "System design and placement planning",
      "Keypad and detector installation",
      "Door contact and sensor setup",
      "Zoning aligned to building use",
      "Monitored and standalone systems",
      "Fault finding and maintenance",
    ],
    featureCards: [
      { title: "Detection", text: "Movement monitored and entry routes covered", icon: "target" },
      { title: "Zoning", text: "Configured around how the building works.", icon: "network" },
      { title: "Support", text: "Servicing and fault response available.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need a more dependable intruder alarm setup?",
    ctaText: "Arrange an alarm review with Helix.",
    ctaButton: "Arrange an Alarm Review",
    ...heroContactUs,
  }),
  makePage({
    slug: "access-control",
    title: "Access Control",
    eyebrow: "Manage who can enter and when",
    intro: [
      "Access control helps clients manage entry across staff doors, communal areas, restricted spaces and managed buildings.",
      "Helix installs and maintains access systems that improve day-to-day control while keeping entry simple for authorised users.",
    ],
    heroImage: "/images/002 - SECURITY SYSTEMS/003 - Access Control Systems/Internal smart storage centre keypad.png",
    heroAlt: "Internal smart storage centre access control keypad",
    sectionTitle: "Access control that supports safer operations",
    sectionBody: [
      "From staff-only areas to communal residential entrances, access control systems help reduce unauthorised entry and improve day-to-day security management.",
      "Helix designs and installs practical access control systems with careful consideration given to device placement, user permissions, and system administration, helping ensure systems remain secure, reliable, and easy to manage.",
      "Supporting safer access, clearer control, and more secure day-to-day operation.",
    ],
    servicesTitle: "Access control services include",
    services: [
      "Door entry systems",
      "Fob and card reader access",
      "Keypad access systems",
      "Maglocks and door hardware",
      "Permissions setup",
      "Servicing and repairs",
    ],
    featureCards: [
      { title: "Control", text: "Manage entry by person, area or time.", icon: "shield" },
      { title: "Visibility", text: "Better oversight of access points.", icon: "target" },
      { title: "Flexible", text: "Systems designed around the building.", icon: "network" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need better control over building access?",
    ctaText: "Talk to Helix about access control options.",
    ctaButton: "Discuss Access Control",
    ...heroContactUs,
  }),
  makePage({
    slug: "intercom-systems",
    title: "Intercom Systems",
    eyebrow: "Clear communication at the entrance",
    intro: [
      "Intercom systems help staff, residents and visitors communicate clearly before access is granted.",
      "Helix supplies, installs and maintains intercom solutions for commercial, residential and managed properties.",
    ],
    heroImage: "/images/002 - SECURITY SYSTEMS/004 - Intercom Systems/External Voice only intercom to residence.png",
    heroAlt: "External voice-only intercom at a residential entrance",
    sectionTitle: "Intercoms for safer, smoother entry",
    sectionBody: [
      "A good intercom system should be reliable, easy to use, and designed around how people access and move through the building.",
      "Helix supports audio, video, and access-linked intercom systems for a wide range of property types.",
      "Helping improve communication, visitor management, and controlled access throughout the property.",
    ],
    servicesTitle: "Intercom support includes",
    services: [
      "Audio intercom installation",
      "Video intercom installation",
      "Door entry integration",
      "Handset and panel replacement",
      "Fault finding and repairs",
      "Maintenance support",
    ],
    featureCards: [
      { title: "Clear", text: "Improve communication before access.", icon: "support" },
      { title: "Secure", text: "Support controlled entry decisions.", icon: "shield" },
      { title: "Reliable", text: "Maintained for daily use.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need an intercom system installed or upgraded?",
    ctaText: "Helix can review your entrance and access needs.",
    ctaButton: "Discuss Intercoms",
    ...heroContactUs,
  }),
  makePage({
    slug: "gate-automation",
    title: "Gate Automation",
    eyebrow: "Controlled access for external entrances",
    intro: [
      "Gate automation supports safer, more convenient access control for car parks, private entrances and managed sites.",
      "Helix helps clients plan, install and maintain gate access solutions that integrate with wider security systems where required.",
    ],
    heroImage: "/images/002 - SECURITY SYSTEMS/005 - Gate Automation/Gate automation on a business park.png",
    heroAlt: "Automated gate access at a business park entrance",
    sectionTitle: "Automated access that supports secure movement",
    sectionBody: [
      "Automated gate systems should be safe, reliable, and suited to how vehicles and pedestrians use the site.",
      "Helix supports the installation, maintenance, repairs, and fault finding of gate automation systems, helping clients manage safe and practical access control.",
      "Supporting smoother site access while maintaining safety and perimeter security.",
    ],
    servicesTitle: "Gate automation support includes",
    services: [
      "Gate automation planning",
      "Access control integration",
      "Intercom integration",
      "Safety device checks",
      "Maintenance and repairs",
      "Fault finding support",
    ],
    featureCards: [
      { title: "Controlled", text: "Manage vehicle access more consistently.", icon: "shield" },
      { title: "Integrated", text: "Connect gates with access systems.", icon: "network" },
      { title: "Maintained", text: "Support safe, reliable operation.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need gate automation support?",
    ctaText: "Talk to Helix about your entrance, site and access requirements.",
    ctaButton: "Discuss Gate Automation",
    ...heroContactUs,
  }),
];

const emergencyPages = [
  makePage({
    slug: "emergency-lighting",
    title: "Emergency Lighting",
    eyebrow: "Safe evacuation when it matters most",
    intro: [
      "Emergency lighting keeps escape routes, exits and key safety areas visible when normal lighting fails.",
      "Helix designs, installs, tests and maintains emergency lighting systems for residential, commercial and managed properties.",
    ],
    heroImage: "/images/003 - EMERGENCY SYSTEMS/001 - Emergency Lighting/Emergency escape lighting - Hospital corridor.png",
    heroAlt: "Emergency escape lighting in a hospital corridor",
    sectionTitle: "Emergency lighting for safe evacuation",
    sectionBody: [
      "Clear visibility can make a critical difference during an emergency evacuation.",
      "Helix assesses escape routes, stairwells, open areas, and higher-risk locations to position emergency lighting where it best supports safe movement and compliance.",
      "Helping occupants navigate escape routes more safely during power loss and emergency situations.",
    ],
    servicesTitle: "Emergency lighting services include",
    services: [
      "Emergency lighting design",
      "Escape route lighting",
      "Open area lighting",
      "Exit sign installation",
      "Testing and maintenance",
      "Certification and documentation",
    ],
    featureCards: [
      { title: "Visible", text: "Routes remain lit during power outages", icon: "target" },
      { title: "Tested", text: "Regular testing and records.", icon: "clipboard" },
      { title: "Supported", text: "Maintenance and repair support.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Keep evacuation routes safe and compliant.",
    ctaText: "Arrange emergency lighting support with Helix.",
    ctaButton: "Discuss Emergency Lighting",
    ...heroContactUs,
  }),
  makePage({
    slug: "emergency-voice-communication-evc",
    title: "Emergency Voice Communication (EVC)",
    eyebrow: "Reliable communication in emergency conditions",
    intro: [
      "Emergency Voice Communication systems help building users and response teams communicate during incidents.",
      "Helix installs and maintains EVC systems for refuge areas, managed buildings and safety-critical environments.",
    ],
    heroImage: "/images/003 - EMERGENCY SYSTEMS/002 - Emergency Voice Communication - EVC/EVC Main Panel -  University lobby.png",
    heroAlt: "EVC main panel in a university lobby",
    sectionTitle: "EVC systems for safer response",
    sectionBody: [
      "Emergency communication systems should be simple to use, reliable, and designed around the building’s emergency response process.",
      "Helix supports the design, installation, commissioning, and maintenance of EVC and disabled refuge communication systems for a wide range of properties.",
      "Helping maintain clear communication and assisted evacuation procedures during emergency situations.",
    ],
    servicesTitle: "EVC support includes",
    services: [
      "EVC system design",
      "Disabled refuge communication",
      "Outstation installation",
      "Control panel setup",
      "Testing and commissioning",
      "Maintenance and repairs",
    ],
    featureCards: [
      { title: "Clear", text: "Communication when it matters most.", icon: "support" },
      { title: "Reliable", text: "Systems tested and maintained.", icon: "shield" },
      { title: "Documented", text: "Service records for managed sites.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need emergency communication support?",
    ctaText: "Talk to Helix about EVC installation or maintenance.",
    ctaButton: "Discuss EVC Systems",
    ...heroContactUs,
  }),
  makePage({
    slug: "nurse-call-systems",
    title: "Nurse Call Systems",
    eyebrow: "Fast support requests in care environments",
    intro: [
      "Nurse call systems help residents, patients and building users request assistance quickly.",
      "Helix designs, installs and maintains nurse call systems for care, assisted living and safety-critical environments.",
    ],
    heroImage: "/images/003 - EMERGENCY SYSTEMS/003 - Nurse Call Systems/Nurse call point beside hospital bed.png",
    heroAlt: "Nurse call point beside a hospital bed",
    sectionTitle: "Nurse call systems designed around response",
    sectionBody: [
      "A nurse call system should be simple for users, reliable in operation, and efficient for staff to manage and respond to.",
      "Helix plans call points, staff alerts, and control panels around the building layout, user needs, and response procedures to support effective day-to-day operation.",
      "Suitable for healthcare, supported living, and managed care environments.",
    ],
    servicesTitle: "Nurse call support includes",
    services: [
      "Nurse call system installation",
      "Pull cord and call point installation",
      "Staff alert panels",
      "Pager system support",
      "Testing and maintenance",
      "Repairs and documentation",
    ],
    featureCards: [
      { title: "Responsive", text: "Help requests routed quickly.", icon: "support" },
      { title: "Practical", text: "Designed around staff workflows.", icon: "network" },
      { title: "Maintained", text: "Regular testing and support.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need a nurse call system installed or maintained?",
    ctaText: "Helix can help plan a dependable communication setup.",
    ctaButton: "Discuss Nurse Call",
    ...heroContactUs,
  }),
  makePage({
    slug: "emergency-escape-route-signage",
    title: "Emergency & Escape Route Signage",
    eyebrow: "Clear direction during evacuation",
    intro: [
      "Emergency and escape route signage helps occupants understand where to go quickly during an incident.",
      "Helix reviews, supplies and positions signage for evacuation routes, exits and safety-critical areas.",
    ],
    heroImage: "/images/003 - EMERGENCY SYSTEMS/004 - Emergency & Escape Route Signage/Emergency signage in apartment corridor.png",
    heroAlt: "Emergency signage in an apartment corridor",
    sectionTitle: "Signage that supports safe evacuation",
    sectionBody: [
      "Escape route signage should be clear, consistent, and easy to understand during an emergency.",
      "Helix helps improve route visibility and wayfinding for occupants while supporting the building’s wider fire safety and evacuation strategy.",
      "Suitable for commercial, residential, and managed property environments.",
    ],
    servicesTitle: "Signage support includes",
    services: [
      "Escape route signs",
      "Emergency exit signs",
      "Directional signage",
      "Fire action notices",
      "Signage placement reviews",
      "Replacement signage",
    ],
    featureCards: [
      { title: "Clear", text: "Simple guidance for safer evacuation.", icon: "target" },
      { title: "Consistent", text: "A joined-up approach across sites.", icon: "clipboard" },
      { title: "Supported", text: "Installed alongside safety surveys", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need emergency route signage support?",
    ctaText: "Helix can review and improve route clarity across your building.",
    ctaButton: "Review Escape Signage",
    ...heroContactUs,
  }),
];

const smartPages = [
  makePage({
    slug: "smart-home-automation",
    title: "Smart Home Automation",
    eyebrow: "Connected control for modern properties",
    intro: [
      "Smart automation helps homes and managed spaces control lighting, access, security and everyday systems more easily.",
      "Helix plans and installs practical smart systems that are reliable, maintainable and appropriate for the property.",
    ],
    heroImage: "/images/004 - SMART SYSTEMS/001 - Smart Home Automation/Smart Home Automation in a modern home 1.png",
    heroAlt: "Smart home automation in a modern home",
    sectionTitle: "Smart systems designed around daily use",
    sectionBody: [
      "Automation should make a property easier to manage, not more complicated.",
      "Helix focuses on dependable setup, clear user controls, and practical integration with security, access control, and connected building systems where beneficial.",
      "Suitable for modern homes, apartments, and connected living environments.",
    ],
    servicesTitle: "Automation support includes",
    services: [
      "Smart control planning",
      "Lighting and access integration",
      "App-based control setup",
      "Device configuration",
      "Network-aware installation",
      "Maintenance support",
    ],
    featureCards: [
      { title: "Connected", text: "Useful controls in one clear setup.", icon: "network" },
      { title: "Practical", text: "Automation matched to the property.", icon: "target" },
      { title: "Supported", text: "Configured for reliable use.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need smart automation for your property?",
    ctaText: "Talk to Helix about a practical connected setup.",
    ctaButton: "Discuss Smart Automation",
    ...heroContactUs,
  }),
  makePage({
    slug: "wi-fi-network-ip-solutions",
    title: "Wi-Fi, Network & IP Solutions",
    eyebrow: "Reliable connectivity for connected systems",
    intro: [
      "Security, access and smart systems rely on dependable connectivity.",
      "Helix supports Wi-Fi, network and IP solutions that help building systems communicate reliably.",
    ],
    heroImage: "/images/004 - SMART SYSTEMS/002 - Wi-Fi  Network & IP Solutions/Wifi network in a modern setting 1.png",
    heroAlt: "Security and network control equipment in a modern building",
    sectionTitle: "Connectivity that supports your systems",
    sectionBody: [
      "From CCTV remote viewing to smart controls and IP-based access systems, reliable connectivity plays an important role in modern buildings.",
      "Helix helps plan practical network and connectivity solutions that support the systems keeping your property secure, connected, and operating smoothly.",
      "Suitable for homes, offices, managed properties, and connected building environments.",
    ],
    servicesTitle: "Network support includes",
    services: [
      "Wi-Fi planning support",
      "IP device configuration",
      "Network points and connectivity",
      "CCTV and access network support",
      "Remote viewing setup",
      "Fault finding support",
    ],
    featureCards: [
      { title: "Connected", text: "Support for IP-enabled systems.", icon: "network" },
      { title: "Reliable", text: "Configured for stable operation.", icon: "shield" },
      { title: "Practical", text: "Planned around building use.", icon: "target" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need Wi-Fi or IP system support?",
    ctaText: "Helix can help connect and configure your building systems.",
    ctaButton: "Discuss Network Support",
    ...heroContactUs,
  }),
  makePage({
    slug: "minor-electrical-works",
    title: "Minor Electrical Works",
    eyebrow: "Supporting safe system installation",
    intro: [
      "Minor electrical works often support fire, security, emergency and smart system installations.",
      "Helix provides practical electrical support where required as part of joined-up building system delivery.",
    ],
    heroImage: "/images/004 - SMART SYSTEMS/003 - Minor Electrical Works/Minor Electrical works 1.png",
    heroAlt: "Minor electrical works supporting building system installation",
    sectionTitle: "Electrical support for safer installations",
    sectionBody: [
      "Small electrical works can play an important role in achieving neat, safe, and reliable system installations.",
      "Helix coordinates minor electrical works alongside wider fire, security, and connected system projects to help keep delivery simpler and more efficient for clients.",
      "Ideal for upgrade works, alterations, repairs, and system additions.",
    ],
    servicesTitle: "Minor works support includes",
    services: [
      "Power support for system equipment",
      "Accessory replacement",
      "Minor wiring works",
      "Safe installation support",
      "Testing and documentation",
      "Fault support",
    ],
    featureCards: [
      { title: "Integrated", text: "Clean and professional installation", icon: "building" },
      { title: "Safe", text: "Work completed with safety in mind.", icon: "shield" },
      { title: "Joined-up", text: "Coordinated with connected systems.", icon: "network" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need minor electrical support with your systems?",
    ctaText: "Talk to Helix about your installation requirements.",
    ctaButton: "Discuss Minor Works",
    ...heroContactUs,
  }),
];

const compliancePages = [
  makePage({
    slug: "certification-compliance",
    title: "Certification & Compliance",
    eyebrow: "Clear documentation for safer buildings",
    intro: [
      "Keeping fire, electrical and safety systems properly tested, certified and documented is essential for responsible property management.",
      "Helix provides practical certification and compliance support for landlords, businesses, facilities managers and property owners.",
    ],
    heroImage: "/images/005 - COMPLIANCE/001 - Certification & Compliance/Certification & Compliance 1.png",
    heroAlt: "Certification and compliance documentation support",
    sectionTitle: "Clear documentation for safer buildings",
    sectionBody: [
      "Compliance is not only about having systems installed — it is about ensuring they are properly tested, maintained, and documented throughout their lifecycle.",
      "Helix provides certification and compliance support with clear reporting and records to assist with safety management, accountability, and ongoing property maintenance.",
      "Supporting landlords, managing agents, businesses, and duty holders with practical compliance management.",
    ],
    servicesTitle: "Certification support includes",
    services: [
      "Fire alarm testing records",
      "Emergency lighting certificates",
      "Fire extinguisher service records",
      "Maintenance documentation",
      "Digital compliance records",
      "Inspection reports",
    ],
    featureCards: [
      { title: "Clear", text: "Documentation that is easier to manage.", icon: "clipboard" },
      { title: "Planned", text: "Support for recurring testing and servicing.", icon: "network" },
      { title: "Accountable", text: "One team managing system records.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need your systems tested, certified or documented?",
    ctaText: "Arrange certification and compliance support with Helix.",
    ctaButton: "Book Compliance Support",
    ...heroContactUs,
  }),
  makePage({
    slug: "safety-inspections-testing",
    title: "Safety Inspections & Testing",
    eyebrow: "Inspections that keep risks visible",
    intro: [
      "Regular inspections and testing help identify faults, gaps and maintenance needs before they become bigger issues.",
      "Helix supports planned safety inspections across fire, emergency, security and electrical support services.",
    ],
    heroImage: "/images/005 - COMPLIANCE/002 - Safety Inspections & Testing/Safety inspections & testing in a modern factory.png",
    heroAlt: "Safety inspections and testing in a modern factory",
    sectionTitle: "Testing and inspection support for managed properties",
    sectionBody: [
      "A well-managed building depends on inspection routines that are practical, consistent, and clearly documented.",
      "Helix helps clients keep inspection records, findings, and recommended actions organised to support ongoing maintenance, safety, and compliance management.",
      "Supporting planned maintenance programmes and ongoing property oversight.",
    ],
    servicesTitle: "Inspection support includes",
    services: [
      "Fire alarm inspections",
      "Emergency lighting tests",
      "Extinguisher checks",
      "AOV operational checks",
      "Security system inspections",
      "Report and record support",
    ],
    featureCards: [
      { title: "Proactive", text: "Issues identified before they escalate.", icon: "target" },
      { title: "Documented", text: "Clear reporting and recommended actions.", icon: "clipboard" },
      { title: "Reliable", text: "Support for planned maintenance programmes.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need safety inspections or system testing?",
    ctaText: "Helix can support planned checks and reporting.",
    ctaButton: "Book Safety Testing",
    ...heroContactUs,
  }),
  makePage({
    slug: "regulatory-compliance-services",
    title: "Regulatory Compliance Services",
    eyebrow: "Practical support for building responsibilities",
    intro: [
      "Keeping buildings compliant requires more than isolated systems — it requires coordinated safety, clear documentation, and dependable ongoing support.",
    ],
    heroImage: "/images/005 - COMPLIANCE/003 - Regulatory Compliance Service/Regulatory Compliance Service 1.png",
    heroAlt: "Regulatory compliance service support",
    sectionTitle: "Compliance support with one accountable team",
    sectionBody: [
      "Our role is to help clients understand what needs attention, what has been completed, and how records should be maintained.",
      "We support landlords, facilities teams, and managed portfolios with practical, ongoing compliance-led service.",
      "We assist clients to maintain clearer oversight across safety systems, testing, and documentation.",
    ],
    servicesTitle: "Regulatory support includes",
    services: [
      "Compliance gap reviews",
      "Maintenance planning",
      "Service documentation",
      "Testing schedules",
      "Portfolio reporting",
      "Fire and security record support",
    ],
    featureCards: [
      { title: "Integrated", text: "Fire, security and compliance aligned.", icon: "network" },
      { title: "Practical", text: "Clear recommendations and actions.", icon: "target" },
      { title: "Documented", text: "Records that support accountability.", icon: "clipboard" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need clearer regulatory compliance support?",
    ctaText: "Talk to Helix about your responsibilities and record keeping.",
    ctaButton: "Book a Compliance Review",
    ...heroContactUs,
  }),
  makePage({
    slug: "portable-appliance-testing-pat",
    title: "Portable Appliance Testing (PAT)",
    eyebrow: "Practical testing and clear records",
    intro: [
      "Portable Appliance Testing helps organisations keep electrical equipment checks organised and documented.",
      "Helix supports PAT testing for offices, managed buildings, commercial environments and property portfolios.",
    ],
    heroImage: "/images/004 - SMART SYSTEMS/004 - Portable Appliance Testing PAT/PAT testing in a factory.png",
    heroAlt: "Portable appliance testing in a commercial environment",
    sectionTitle: "PAT testing that supports organised records",
    sectionBody: [
      "PAT testing should be straightforward, practical, and easy to evidence through clear reporting and record management.",
      "Helix helps clients keep portable appliance testing records up to date as part of wider maintenance, safety, and compliance support.",
      "Suitable for offices, schools, retail premises, warehouses, and other working environments using portable electrical equipment.",
    ],
    servicesTitle: "PAT support includes",
    services: [
      "Portable appliance testing",
      "Equipment labelling",
      "Test records",
      "Asset list support",
      "Failed item reporting",
      "Planned retesting schedules",
    ],
    featureCards: [
      { title: "Tested", text: "Equipment checks completed professionally.", icon: "check" },
      { title: "Documented", text: "Records prepared for review and compliance.", icon: "clipboard" },
      { title: "Planned", text: "Support for recurring testing schedules.", icon: "shield" },
    ],
    suitableFor: commonSuitableFor,
    ctaTitle: "Need PAT testing for your property or portfolio?",
    ctaText: "Helix can help keep appliance testing organised.",
    ctaButton: "Book PAT Testing",
    ...heroContactUs,
  }),
];

function makeLanding(
  group: string,
  slug: string,
  title: string,
  eyebrow: string,
  intro: string[],
  heroImage: string,
  pages: PremiumServicePageData[],
  overrides?: Partial<PremiumServicePageData>,
): PremiumServicePageData {
  return makePage({
    slug,
    title,
    eyebrow,
    intro,
    heroImage,
    heroAlt: `${title} services from Helix`,
    sectionTitle: `Complete ${group.toLowerCase()} support for your property`,
    sectionBody: [
      "Every building has different risks, usage patterns and responsibilities. Helix reviews your property carefully and recommends practical systems and support that fit the way the site operates.",
      "Our team keeps the process clear from survey and design through installation, maintenance and documentation.",
    ],
    servicesTitle: `Explore ${group.toLowerCase()} services`,
    services: pages.map((page) => page.title),
    featureCards: pages.slice(0, 3).map((page, index) => ({
      title: page.title,
      text: page.eyebrow,
      icon: ["target", "network", "shield"][index] ?? "shield",
    })),
    suitableFor: commonSuitableFor,
    ctaTitle: `Need ${group.toLowerCase()} support for your building?`,
    ctaText: "Talk to Helix today and we will help shape the right next step.",
    ctaButton: "Book a Survey",
    ...overrides,
  });
}

export const serviceGroups: Record<ServiceGroupKey, ServiceGroup> = {
  fire: {
    key: "fire",
    route: "/fire-systems",
    label: "Fire Systems",
    theme: { category: "Fire Systems", categoryHref: "/fire-systems", accent: "#EF2B2D", accentDark: "#B91C1C", label: "Fire" },
    landing: makeLanding(
      "Fire Systems",
      "fire-systems",
      "Fire Systems",
      "Complete fire protection support",
      [
        "Helix provides fire systems that protect people, property and day-to-day operations.",
        "From alarms and extinguishers to smoke ventilation and signage, our team delivers practical fire safety support.",
      ],
      "/images/001 - FIRE SYSTEMS/Image for main fire systems page - reception scene.png",
      firePages,
      {
        sectionBody: [
          "Every building operates differently, with its own risks, occupancy patterns and compliance responsibilities. Helix carefully assesses each property and recommends practical fire, security and compliance solutions suited to how the site is used and managed.",
          "From initial survey and system design through to installation, maintenance and documentation, our team keeps the process clear, organised and professionally managed at every stage.",
          "Clear communication, dependable workmanship and consistent support remain central to every project we deliver.",
        ],
        services: [
          ...firePages.map((page) => page.title),
          "Fire Alarm Servicing and Maintenance",
          "Assessments tailored to the building layout",
        ],
        ctaButton: "Discuss Fire Systems",
        ...heroContactUs,
      },
    ),
    pages: firePages,
  },
  security: {
    key: "security",
    route: "/security",
    label: "Security Systems",
    theme: { category: "Security Systems", categoryHref: "/security", accent: "#2855C7", accentDark: "#1D3F99", label: "Security" },
    landing: makeLanding(
      "Security Systems",
      "security",
      "Security Systems",
      "Protection, access and monitoring",
      [
        "Helix designs, installs and maintains security systems that improve visibility, controlled access and response planning.",
        "Our solutions are configured around the way your property is used, occupied and managed.",
      ],
      "/images/002 - SECURITY SYSTEMS/Image for main security systems page - warehouse scene.png",
      securityPages,
      {
        sectionBody: [
          "Every building has different risks, usage patterns and compliance responsibilities. Helix carefully reviews each property and recommends practical systems and support tailored to the way the site operates.",
          "From initial survey and system design through to installation, maintenance and documentation, our team keeps the process clear, organised and professionally managed throughout.",
          "Practical advice, reliable workmanship and long-term support remain at the centre of our approach.",
        ],
        featureCards: [
          { title: securityPages[0].title, text: "Visual coverage that supports real time oversight", icon: "target" },
          { title: securityPages[1].title, text: securityPages[1].eyebrow, icon: "network" },
          { title: securityPages[2].title, text: securityPages[2].eyebrow, icon: "shield" },
        ],
        ctaButton: "Discuss Security Systems",
        ...heroContactUs,
      },
    ),
    pages: securityPages,
  },
  emergency: {
    key: "emergency",
    route: "/emergency-systems",
    label: "Emergency Systems",
    theme: { category: "Emergency Systems", categoryHref: "/emergency-systems", accent: "#EF2B2D", accentDark: "#B91C1C", label: "Emergency" },
    landing: makeLanding(
      "Emergency Systems",
      "emergency-systems",
      "Emergency Systems",
      "Safe response when it matters",
      [
        "Helix supports emergency systems that help people evacuate, communicate and request support quickly.",
        "From emergency lighting and EVC to nurse call and escape route signage, we keep safety-critical systems clear and reliable.",
      ],
      "/images/003 - EMERGENCY SYSTEMS/Image for main emergency systems page - hospital scene.png",
      emergencyPages,
      {
        sectionBody: [
          "Every building has different risks, usage patterns and responsibilities. Helix reviews your property carefully and recommends practical systems and support that fit the way the site operates.",
          "Our team keeps the process clear from survey and design through installation, maintenance and documentation.",
        ],
        ctaButton: "Discuss Emergency Systems",
        ...heroContactUs,
      },
    ),
    pages: emergencyPages,
  },
  smart: {
    key: "smart",
    route: "/smart-systems",
    label: "Smart Systems",
    theme: { category: "Smart Systems", categoryHref: "/smart-systems", accent: "#2855C7", accentDark: "#1D3F99", label: "Smart" },
    landing: makeLanding(
      "Smart Systems",
      "smart-systems",
      "Smart Systems",
      "Connected building support",
      [
        "Helix supports smart, networked and electrical services that help modern properties operate more smoothly.",
        "We focus on practical systems that are reliable, maintainable and easy for clients to manage.",
      ],
      "/images/004 - SMART SYSTEMS/Image for main smart systems page - modern home scene.png",
      smartPages,
      {
        sectionBody: [
          "Every building has different risks, usage patterns and compliance responsibilities. Helix carefully reviews each property and recommends practical systems and support that fit the way the site operates.",
          "Our team keeps the process clear from initial survey and design through to installation, maintenance and documentation.",
          "The result is a more organised, compliant and confidently managed environment for building owners and occupants alike.",
        ],
        ctaButton: "Discuss Smart Systems",
        ...heroContactUs,
      },
    ),
    pages: smartPages,
  },
  compliance: {
    key: "compliance",
    route: "/compliance",
    label: "Compliance",
    theme: { category: "Compliance", categoryHref: "/compliance", accent: "#198754", accentDark: "#11683F", label: "Compliance" },
    landing: makeLanding(
      "Compliance",
      "compliance",
      "Compliance",
      "Certification, inspections and records",
      [
        "Helix helps clients manage fire, security and compliance responsibilities with clearer systems, organised reporting and dependable ongoing support.",
      ],
      "/images/005 - COMPLIANCE/Image for main compliance page - office scene.png",
      compliancePages,
      {
        sectionBody: [
          "Every building has different risks, usage patterns and compliance responsibilities. Helix carefully reviews each property and recommends practical systems and support that fit the way the site operates.",
          "Our team keeps the process clear from survey and design through to installation, maintenance and documentation.",
          "A well planned system is easier to manage, easier to maintain and better suited to the people who rely on it every day.",
        ],
        featureCards: [
          { title: compliancePages[0].title, text: compliancePages[0].eyebrow, icon: "target" },
          { title: compliancePages[1].title, text: "Ongoing support to meet building regulations", icon: "network" },
          { title: compliancePages[2].title, text: compliancePages[2].eyebrow, icon: "shield" },
        ],
        ctaButton: "Discuss Compliance",
        ...heroContactUs,
      },
    ),
    pages: compliancePages,
  },
};

export function getServiceGroup(key: ServiceGroupKey) {
  return serviceGroups[key];
}

export function getServicePage(key: ServiceGroupKey, slug: string) {
  return serviceGroups[key].pages.find((page) => page.slug === slug);
}
